spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password: Rasikai2i*
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
  logging:
    file: logs/application-debug.log
    pattern:
      console: "%d %-5level %logger : %msg%n"
      file: "%d %-5level [%thread] %logger : %msg%n"
    level:
      org.springframework.web: ERROR
      com.ideas2it.employee: DEBUG
      org.hibernate: ERROR

