spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password: Rasikai2i*
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate :
        auto-ddl : create
        show-sql : true
        dialect : org.hibernate.dialect.MySQL5Dialect

